AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4.1
  Exclude:
    - bin/**/*

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Layout/LineLength:
  Max: 100