# frozen_string_literal: true

source 'https://rubygems.org'

group :development, :test do
  gem 'rspec'
  gem 'rubocop'
  gem 'simplecov', require: false
  gem 'simplecov-lcov', require: false

  # Sorbet gems
  gem 'sorbet', platforms: %i[ruby mswin mingw x64_mingw]
  gem 'sorbet-static-and-runtime'
  gem 'tapioca', require: false # Optional: for generating RBI files
end
ruby file: File.expand_path('.ruby-version', __dir__)
