# frozen_string_literal: true

source 'https://rubygems.org'

gem 'rbs'
gem 'steep' 
gem 'sorbet', :group => :development
gem 'sorbet-runtime'
gem 'tapioca', require: false, :group => [:development, :test]
gem 'rspec'
gem 'rubocop', require: false
gem 'simplecov'

ruby file: File.expand_path('.ruby-version', __dir__)
