name: Go tests

on:
  push:
    paths:
      - 'go/**'
      - '.github/workflows/go.yml'
  pull_request:
    paths:
      - 'go/**'
      - '.github/workflows/go.yml'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./go

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Install dependencies
        run: go mod download

      - name: Run unit tests
        run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          file: ./coverage.txt
          token: ${{ secrets.CODECOV_TOKEN }}