name: python tests

on:
  push:
    paths:
      - 'python/**'
      - '.github/workflows/python.yml'
  pull_request:
    paths:
      - 'python/**'
      - '.github/workflows/python.yml'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./python

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.1"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Tests
        run: python -m unittest discover
